POST http://localhost:3001/channels/3 HTTP/1.1
content-type: application/json

{
  "message": "lorem impsum"
}

###
GET http://localhost:3001/channels HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/messages/2 HTTP/1.1
content-type: application/json


